# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '11'

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.DEPLOYMENT_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}


    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Show Branch Name
      shell: bash
      run: echo "${{ steps.extract_branch.outputs.branch }}"

    - name: Run a multi-line script
      run: |
        cd wp-content/themes/mission-blvd-club/
        yarn install
        yarn build-production
        git config --global user.name "Willis Allstead"
        git config --global user.email "willallstead@icloud.com"
        git add -f ./dist
        git commit -am 'CI Build ⚒️'
        if [ "$CURRENT_BRANCH" == "master" ]; then
          git push git@git.wpengine.com:production/mssnblvdclub.git master -f
        elif [ "$CURRENT_BRANCH" == "staging" ]; then
          git push git@git.wpengine.com:production/mssnblvdstage.git staging -f
        fi
      env:
        CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
